oauth:
  client_id: "client_service"
  client_secret: "$2a$10$HlSlN056SVcxDNeGort5x."
  id_token_secret: "id_token_secret"
  id_service_url: "localhost:3013/oauth"
  id_token_service_url: "localhost:3013/oauth"
  id_logout_service_url: "localhost:3013/logout"  
  id_userinfo_service_url: "localhost:3013/userinfo"  