# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bba67c506b1ab7998fccfcdd11bef0ddaaee381b2ce0613b9e6b0b3bd59e753be37f865aab3dcb21526ef360ebf8b04688641fea9c5c7618a48e1d1f69fffad0

test:
  secret_key_base: ebb01224ec5a0a50121358afcc16ccadcee57c58cbce6d8a24e14744302ee60c2352f6570011f8e8409b75be1e8484e7914722bf514e5152bf0176b5c0286295

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
